"""empty message

Revision ID: 4492ad0edf07
Revises: 61e1e5d9ee7b
Create Date: 2017-08-29 06:11:59.936401

"""

# revision identifiers, used by Alembic.
revision = '4492ad0edf07'
down_revision = '61e1e5d9ee7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lang', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lang')
    # ### end Alembic commands ###
