"""empty message

Revision ID: 54a154a8ece6
Revises: 4492ad0edf07
Create Date: 2017-09-01 05:23:51.281979

"""

# revision identifiers, used by Alembic.
revision = '54a154a8ece6'
down_revision = '4492ad0edf07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('competitor', 'gender')
    #op.add_column('competitor', sa.Column('gender', sa.String(length=1), nullable=True))
    #op.drop_constraint(None, 'competitor', type_='foreignkey')
    #op.drop_column('competitor', 'gender_id')
    op.add_column('marks', sa.Column('description', sa.String(length=100), nullable=True))
    op.drop_column('marks', 'desciption')
    op.add_column('status', sa.Column('description', sa.String(length=100), nullable=True))
    op.drop_column('status', 'desciption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('desciption', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('status', 'description')
    op.add_column('marks', sa.Column('desciption', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('marks', 'description')
    op.add_column('competitor', sa.Column('gender_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'competitor', 'gender', ['gender_id'], ['id'])
    op.drop_column('competitor', 'gender')
    # ### end Alembic commands ###
