"""empty message

Revision ID: 61e1e5d9ee7b
Revises: d66f086b258
Create Date: 2017-08-25 04:51:51.374917

"""

# revision identifiers, used by Alembic.
revision = '61e1e5d9ee7b'
down_revision = 'd66f086b258'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('td', sa.Column('en_nation', sa.String(), nullable=True))
    op.add_column('td', sa.Column('ru_nation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('td', 'ru_nation')
    op.drop_column('td', 'en_nation')
    # ### end Alembic commands ###
