"""empty message

Revision ID: f422a70e14f7
Revises: 9ba73870d3e1
Create Date: 2018-07-06 00:46:56.742746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f422a70e14f7'
down_revision = '9ba73870d3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('race_competitor_run_id_fkey', 'race_competitor', type_='foreignkey')
    op.create_foreign_key(None, 'race_competitor', 'run_info', ['run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'race_competitor', type_='foreignkey')
    op.create_foreign_key('race_competitor_run_id_fkey', 'race_competitor', 'run_info', ['run_id'], ['id'])
    # ### end Alembic commands ###
